return require("packer").startup(function(use)

    use "wbthomason/packer.nvim"
    use "kyazdani42/nvim-tree.lua"
    use "akinsho/toggleterm.nvim"
    use "nvim-lualine/lualine.nvim"
    use "kyazdani42/nvim-web-devicons"
    use "nvim-telescope/telescope.nvim"
    use "nvim-lua/plenary.nvim"
    use "windwp/nvim-autopairs"
    use "windwp/nvim-ts-autotag"
    use "catppuccin/nvim"
    use "williamboman/mason.nvim"
    use "williamboman/mason-lspconfig.nvim"
    use "neovim/nvim-lspconfig"
    use "hrsh7th/nvim-cmp"
    use "hrsh7th/cmp-nvim-lsp"
    use "saadparwaiz1/cmp_luasnip"
    use "L3MON4D3/LuaSnip"
    use "onsails/lspkind.nvim"
    use "akinsho/bufferline.nvim"
    use "nvim-treesitter/nvim-treesitter"
    use "nvim-treesitter/nvim-treesitter-textobjects"
    use "folke/neodev.nvim"
    use "j-hui/fidget.nvim"
    use "tpope/vim-fugitive"
    use "tpope/vim-rhubarb"
    use "lewis6991/gitsigns.nvim"
    use "lukas-reineke/indent-blankline.nvim"
    use "numToStr/Comment.nvim"
    use "tpope/vim-sleuth"
    use "glepnir/lspsaga.nvim"
    use "norcalli/nvim-colorizer.lua"
    use "Pocco81/true-zen.nvim"

end)
